steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/angular-app-engine:${SHORT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/angular-app-engine"]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'angular-app-engine', '--image', 'gcr.io/$PROJECT_ID/angular-app-engine:${SHORT_SHA}', '--region', 'europe-west3']
