steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/angular-starter:${SHORT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/angular-starter"]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'angular-starter', '--image', 'gcr.io/$PROJECT_ID/angular-starter:${SHORT_SHA}', '--region', 'us-central1']
